/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Coredise
 */
public class cambioEmpresa extends javax.swing.JPanel {

    /**
     * Creates new form cambioEmpresa
     */
    private Dimension dim;
    public cambioEmpresa() {
        initComponents();
        ubicacion();
        
    }
    public void ubicacion(){
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        //para obtener las dimensiones de la pantalla
        Dimension dimen = this.getSize();
        //igual pero para la ventana
        this.setLocation(
            (pantalla.width - dimen.width) / 2,
            (pantalla.height - dimen.height) / 2);
        
    }
    public void Ventana(){
        //con esto obtienes en tamano en en x y y de tu monitor
        dim=super.getToolkit().getScreenSize();
        super.setSize(dim);
//        super.setUndecorated(true);
//        super.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setMinimumSize(new java.awt.Dimension(500, 500));
        jComboBox1.setPreferredSize(new java.awt.Dimension(500, 500));
        add(jComboBox1);
        jComboBox1.setBounds(260, 220, 240, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cambioEmpresa.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 800));
        jLabel1.setName(""); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 870, 560);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
