/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Coredise
 */
public class main extends javax.swing.JFrame {
    private Dimension dim;
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        ubicacion();
    }
    public void ubicacion(){
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        //para obtener las dimensiones de la pantalla
        Dimension dimen = this.getSize();
        //igual pero para la ventana
        this.setLocation(
            (pantalla.width - dimen.width) / 2,
            (pantalla.height - dimen.height) / 2);
        
    }
    public void Ventana(){
        //con esto obtienes en tamano en en x y y de tu monitor
        dim=super.getToolkit().getScreenSize();
        super.setSize(dim);
//        super.setUndecorated(true);
//        super.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bModificacion = new javax.swing.JButton();
        bConsulta = new javax.swing.JButton();
        bOrden = new javax.swing.JButton();
        bInicio = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bReportar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(5);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1520, 1000));
        getContentPane().setLayout(null);

        bModificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bModificacion.png"))); // NOI18N
        bModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificacionActionPerformed(evt);
            }
        });
        getContentPane().add(bModificacion);
        bModificacion.setBounds(1000, 90, 190, 50);

        bConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bConsulta.png"))); // NOI18N
        bConsulta.setMaximumSize(new java.awt.Dimension(223, 63));
        bConsulta.setMinimumSize(new java.awt.Dimension(223, 63));
        bConsulta.setPreferredSize(new java.awt.Dimension(223, 63));
        bConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(bConsulta);
        bConsulta.setBounds(710, 90, 190, 50);

        bOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bOrdenes.png"))); // NOI18N
        bOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(bOrden);
        bOrden.setBounds(410, 90, 190, 50);

        bInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bInicio.png"))); // NOI18N
        bInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicioActionPerformed(evt);
            }
        });
        getContentPane().add(bInicio);
        bInicio.setBounds(0, 340, 360, 130);

        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bSalir.png"))); // NOI18N
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        getContentPane().add(bSalir);
        bSalir.setBounds(0, 580, 360, 130);

        bReportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bReportarError.png"))); // NOI18N
        bReportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReportarActionPerformed(evt);
            }
        });
        getContentPane().add(bReportar);
        bReportar.setBounds(0, 470, 360, 120);

        jLabel1.setText("EMPRESA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 50, 170, 170);

        jLabel2.setFont(new java.awt.Font("Arcon", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("nombre de empresa");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 240, 260, 40);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mainFinal.png"))); // NOI18N
        fondo.setMaximumSize(new java.awt.Dimension(1567, 970));
        fondo.setMinimumSize(new java.awt.Dimension(1567, 970));
        fondo.setOpaque(true);
        fondo.setPreferredSize(new java.awt.Dimension(1567, 970));
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 1800, 980);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdenActionPerformed
        //Establece imagen de color verde para que se note seleccion
        
        bOrden.setIcon(new ImageIcon("src/imagenes/bOrdenPressed.png"));
        bConsulta.setIcon(new ImageIcon("src/imagenes/bConsulta.png"));
        bModificacion.setIcon(new ImageIcon("src/imagenes/bModificacion.png"));
        //Establece resto de botones como desactivados
        
        
    }//GEN-LAST:event_bOrdenActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        ImageIcon cambio= new ImageIcon("src/imagenes/bSalirPressed.png");
        bSalir.setIcon(cambio);
        bInicio.setIcon(new ImageIcon("src/imagenes/bInicio.png"));
        bReportar.setIcon(new ImageIcon("src/imagenes/bReportarError.png"));
        dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicioActionPerformed
        ImageIcon cambio= new ImageIcon("src/imagenes/bInicioPressed.png");
        bInicio.setIcon(cambio);
        bReportar.setIcon(new ImageIcon("src/imagenes/bReportarError.png"));
        bSalir.setIcon(new ImageIcon("src/imagenes/bSalir.png"));
    }//GEN-LAST:event_bInicioActionPerformed

    private void bReportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReportarActionPerformed
        ImageIcon cambio= new ImageIcon("src/imagenes/bReportarErrorPressed.png");
        bReportar.setIcon(cambio);
        bInicio.setIcon(new ImageIcon("src/imagenes/bInicio.png"));
        bSalir.setIcon(new ImageIcon("src/imagenes/bSalir.png"));
        
        cambioDeEmpresa e1 = new cambioDeEmpresa();
        e1.setVisible(true);
    }//GEN-LAST:event_bReportarActionPerformed

    private void bConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultaActionPerformed
        bOrden.setIcon(new ImageIcon("src/imagenes/bOrdenes.png"));
        bConsulta.setIcon(new ImageIcon("src/imagenes/bConsultaPressed.png"));
        bModificacion.setIcon(new ImageIcon("src/imagenes/bModificacion.png"));
    }//GEN-LAST:event_bConsultaActionPerformed

    private void bModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificacionActionPerformed
        bOrden.setIcon(new ImageIcon("src/imagenes/bOrdenes.png"));
        bConsulta.setIcon(new ImageIcon("src/imagenes/bConsulta.png"));
        bModificacion.setIcon(new ImageIcon("src/imagenes/bModificacionPressed.png"));
    }//GEN-LAST:event_bModificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConsulta;
    private javax.swing.JButton bInicio;
    private javax.swing.JButton bModificacion;
    private javax.swing.JButton bOrden;
    private javax.swing.JButton bReportar;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
