/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import conexionBD.conexionBD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import menu.main;

/**
 *
 * @author Coredise
 */
public class login extends javax.swing.JFrame {
    int contUser=0;
    int contPass=0;
    /**
     * Creates new form login
     */
    public login() {
        
        initComponents();
        ubicacion();
        
               
        usuario.setOpaque(true);
        usuario.setBorder(null);
        pass.setOpaque(true);
        pass.setBorder(null);
        ingresar.setOpaque(true);
        ingresar.setBorder(null);
        salir.setOpaque(true);
        salir.setBorder(null);
    }
    public void ubicacion(){
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        //para obtener las dimensiones de la pantalla
        Dimension dimen = this.getSize();
        //igual pero para la ventana
        this.setLocation(
            (pantalla.width - dimen.width) / 2,
            (pantalla.height - dimen.height) / 2);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();
        usuario = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        ingresar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(5, 0));
        setMinimumSize(new java.awt.Dimension(700, 780));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        salir.setBackground(null);
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(650, 0, 50, 50);

        usuario.setBackground(new java.awt.Color(209, 209, 209));
        usuario.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        usuario.setText("Usuario");
        usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioMouseClicked(evt);
            }
        });
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuarioKeyPressed(evt);
            }
        });
        getContentPane().add(usuario);
        usuario.setBounds(180, 340, 410, 60);
        usuario.getAccessibleContext().setAccessibleName("");

        pass.setBackground(new java.awt.Color(209, 209, 209));
        pass.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        pass.setText("textoo");
        pass.setOpaque(false);
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passMouseClicked(evt);
            }
        });
        getContentPane().add(pass);
        pass.setBounds(180, 440, 420, 60);

        ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton.png"))); // NOI18N
        ingresar.setText("jButton1");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(ingresar);
        ingresar.setBounds(180, 560, 340, 60);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loginv3.png"))); // NOI18N
        fondo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fondoKeyPressed(evt);
            }
        });
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 700, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMouseClicked
        
        if(contUser==0){
            usuario.setText(null);
            contUser++;
        }   
        
    }//GEN-LAST:event_usuarioMouseClicked

    private void usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyPressed
        
    }//GEN-LAST:event_usuarioKeyPressed

    private void fondoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fondoKeyPressed
     
    }//GEN-LAST:event_fondoKeyPressed

    private void passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseClicked
        if(contPass==0){
            pass.setText(null);
            contPass++;
        }  
    }//GEN-LAST:event_passMouseClicked

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        
        char [] pass1 = pass.getPassword();
        String clave = new String(pass1);
        if(usuario.getText().isEmpty()&& clave.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingresar usuario y contraseña");
            
        }
        else{
            conexionBD conectar = new conexionBD();
            Statement st = conectar.conexion();
        }
        conexionBD conectar = new conexionBD();
        Statement st = conectar.conexion();
        try{
            ResultSet rs = st.executeQuery("SELECT * FROM USUARIOS Where nom_user='"+usuario.getText()+"'and pass_user='"+clave+"'");
            rs.last();
            int encontrado = rs.getRow();

            if (encontrado == 1){
                System.out.println("exitoso");
                //Se habilitaria el menu principal
                main m1 = new main();
                m1.setVisible(true);
                hide();
            }
            else{
                usuario.setText(null);
                pass.setText(null);
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecta");
                
                
            }
        }catch(SQLException ex){
            System.err.println(ex);
        }
    }//GEN-LAST:event_ingresarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        dispose();
    }//GEN-LAST:event_salirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton ingresar;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton salir;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

    private int getKeyCode() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
